### ISSUE TITLE
Npm version specification.

### ISSUE THREAD

**Issue by ManishJu** [maierfelix/WebGPU-Path-Tracer#1]
Could you please specify which version of node this project run on .
as running using "npm install" the latest stable version is giving  ->

```
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN notsup Unsupported engine for webgpu@0.1.13: wanted: {"node":">= 13.0.0"} (current: {"node":"12.16.3","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: webgpu@0.1.13
npm WARN WebGPU-Path-Tracer No repository field.
npm WARN WebGPU-Path-Tracer No license field.

added 5 packages from 3 contributors and audited 5 packages in 2.61s
found 0 vulnerabilities
```
and on running gives :

```
> @ start /home/mj/Downloads/All git/WebGPU-Path-Tracer
> node index.mjs

internal/modules/cjs/loader.js:975
    throw new ERR_REQUIRE_ESM(filename);
    ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/mj/Downloads/All git/WebGPU-Path-Tracer/index.mjs
    at Module.load (internal/modules/cjs/loader.js:975:11)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  code: 'ERR_REQUIRE_ESM'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ start: `node index.mjs`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mj/.npm/_logs/2020-05-03T15_43_38_519Z-debug.log

```

and using the latest 14.1 version is giving the following errors ->

```
Warning: Couldn't open libvulkan.so.1
Info: Couldn't load Vulkan
(node:5563) UnhandledPromiseRejectionWarning: Error: Unknown failure
    at main (file:///home/mj/Downloads/All%20git/WebGPU-Path-Tracer/index.mjs:36:27)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:5563) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:5563) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I am running on Ubunut 18 + nvidia rtx with driver version 335

Thanks !

**Comment by maierfelix** [comment]
I'm using node `13.9.0` but that shouldn't be the problem. It seems that the project cannot load Vulkan from your system, do you have Vulkan installed? Also notice that you need the [Vulkan beta driver](https://developer.nvidia.com/vulkan-beta-4406611-linux) to run this project.

**Comment by ManishJu** [comment]
It is so difficult to get these experimental Vulkan drivers installed on both Windows and Linux.
On Windows (using the windows experimental driver) I get a no-support from the nvidia maybe because I am on a laptop.
On Ubuntu the X window system is giving me problems. 
Thanks for your help in between. I will get this driver issue solved as soon as I can. When do you think this will be out of experimental phase ?

**Comment by maierfelix** [comment]
I'm on a laptop too and didn't have any problems regarding the beta driver on Windows.
> When do you think this will be out of experimental phase ?

As soon as the VK_KHR_ray_tracing extension leaves beta. Shouldn't be too long from now

**Comment by ManishJu** [comment]
got it running with the exact driver version 443 for windows , not higher drivers versions like 445 are working.
![1](https://user-images.githubusercontent.com/24234466/81463543-23db4400-91b2-11ea-877a-5b7cd4f5a327.jpg)

**Comment by maierfelix** [comment]
Yes, you need the beta drivers right now. The beta drivers have lower version numbers than the official ones.
